redactions = ["API_KEY", "PASSWORD"]

[task_config]

includes = [
    ".mise/tasks",
    "mise/tasks-git",
    "mise/tasks-podman",
    "mise/tasks-shell",
]

[tools]
go = "latest"
golangci-lint = "latest"

[env]
DEV_DATA_DIR = ".mise"
DEV_NOTES_DIR = ".mise/notes"

# Deploy tasks defaults
DEPLOY_SERVICE_NAME = "picoclaw"
# BUILD_NEXT = "build-next"
# BUILD_CURRENT = "build-current"
# BUILD_PREV = "build-prev"
DEPLOY_STATUS_DIR = "$HOME/.picoclaw"
